# Generated by Django 4.2.4 on 2023-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Order',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='TS5VP11D', max_length=10),
        ),
    ]
