# Generated by Django 4.2.4 on 2023-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_cartdetail_quantity_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='9EUO2DQP', max_length=10),
        ),
    ]
