# Generated by Django 4.2.4 on 2023-10-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_code_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='total_after_coupon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='Y6D6F2EK', max_length=10),
        ),
    ]
