# Generated by Django 4.2.4 on 2023-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='total_after_coupon',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_after_coupon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='LDFK9EA0', max_length=10),
        ),
    ]
