# Generated by Django 4.2.4 on 2023-10-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_cartdetail_total_after_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='YVO6EQGY', max_length=10),
        ),
    ]
