# Generated by Django 4.2.4 on 2023-10-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Coupon',
            new_name='coupon',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='5SBLTMBS', max_length=10),
        ),
    ]
