# Generated by Django 4.2.4 on 2023-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_coupon_cart_coupon_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='3FURN765', max_length=10),
        ),
    ]
