# Generated by Django 4.2.4 on 2023-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='BZ0X1XZZ', max_length=10),
        ),
    ]
