# Generated by Django 4.2.4 on 2023-11-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='8UYXJ3D9', max_length=10),
        ),
    ]
